import Head from 'next/head';
import React from 'react';
import { NextPage } from 'next';
import { getAntDesignColor } from '@/frontend/styles/colors';
import { Colors } from '@prisma/client';

const bg = getAntDesignColor(Colors.NEUTRAL)[0];

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main style={{ backgroundColor: bg, minHeight: '100vh' }}>
      </main>
    </>
  );
};

export default Home;
